---
- name: add R apt repository
  lineinfile: dest=/etc/apt/sources.list line="deb http://cran.cnr.berkeley.edu/bin/linux/ubuntu trusty/"
  sudo: yes

- name: add R apt key
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  sudo: yes

- name: install R
  apt: update_cache=yes cache_valid_time=600 name=r-base,r-base-dev state=latest
  sudo: yes

- name: Rprofile configuration
  copy: src=Rprofile.site dest=/etc/R/Rprofile.site mode=0644
  sudo: yes

- name: Renviron configuration
  copy: src=Renviron.site dest=/etc/R/Renviron.site mode=0644
  sudo: yes

- name: install packages for R kernel installation
  apt: update_cache=yes cache_valid_time=600 name=libzmq3-dev,libcurl4-openssl-dev state=latest
  sudo: yes

# from http://adamj.eu/tech/2014/07/19/installing-and-removing-r-packages-with-ansible/
- name: install devtools
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', lib='/usr/local/lib/R/site-library'); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - devtools
    - RCurl
  sudo: yes

- name: install IRkernel
  command: >
    Rscript --slave --no-save --no-restore-history -e "library(devtools); if (! ('{{ item.package }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item.user }}/{{ item.package }}', lib='/usr/local/lib/R/site-library'); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - { user: armstrtw, package: rzmq }
    - { user: takluyver, package: IRdisplay }
    - { user: takluyver, package: IRkernel }
  sudo: yes
