---
- name: add R apt repository
  lineinfile: dest=/etc/apt/sources.list line="deb http://cran.cnr.berkeley.edu/bin/linux/ubuntu trusty/"

- name: add R apt key
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

- name: install R
  apt: update_cache=yes cache_valid_time=600 name=r-base,r-base-dev state=latest

- name: Rprofile configuration
  copy: src=Rprofile.site dest=/etc/R/Rprofile.site mode=0644

- name: Renviron configuration
  copy: src=Renviron.site dest=/etc/R/Renviron.site mode=0644

- name: install packages for R kernel installation
  apt: update_cache=yes cache_valid_time=600 name=libzmq3-dev,libcurl4-openssl-dev,libssl-dev state=latest

# from http://adamj.eu/tech/2014/07/19/installing-and-removing-r-packages-with-ansible/
- name: install devtools
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}'); print('Added'); } else { print('Already installed'); }"
  register: r_result
  changed_when: "'Added' in r_result.stdout"
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  with_items:
    - repr
    - IRdisplay
    - crayon
    - pdbZMQ
    - devtools
    - stringi

- name: install IRkernel
  command: >
    Rscript --slave --no-save --no-restore-history -e "devtools::install_github('IRkernel/IRkernel'); IRkernel::installspec()"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
