---
- name: create admin accounts
  user:
    name: "{{ item }}"
    group: jupyterhub_admins
  with_items: admins
  sudo: yes

- name: create user accounts
  user:
    name: "{{ item }}"
    group: jupyterhub_users
  with_items: users
  sudo: yes
