---
- name: install packages with apt-get
  apt: name={{ item }} update_cache=yes state=installed
  with_items:
    - npm
    - nodejs-legacy
    - daemon

- name: install bower
  npm: name=bower global=yes

- name: install less
  npm: name=less global=yes version=1.7.5

- name: install jupyter/configurable-http-proxy
  npm: name=jupyter/configurable-http-proxy global=yes

- name: create the jupyterhub directory
  file: path={{ root }} state=directory
