---
- name: add nodejs apt repo
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

- name: install packages with apt-get
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - nodejs
    - daemon

- name: install bower
  npm: name=bower global=yes

- name: install less
  npm: name=less global=yes version=1.7.5

- name: install jupyter/configurable-http-proxy
  npm: name=jupyter/configurable-http-proxy global=yes

- name: install jupyterhub
  pip: name=jupyterhub state=latest executable=/usr/local/bin/pip3

- name: create the jupyterhub directory
  file: path={{ jupyterhub_root }} state=directory
