---
- name: install packages with apt-get
  apt: name={{ item }} update_cache=yes state=installed
  sudo: yes
  with_items:
    - npm
    - nodejs-legacy
    - daemon

- name: install bower
  npm: name=bower global=yes
  sudo: yes

- name: install less
  npm: name=less global=yes version=1.7.5
  sudo: yes

- name: install jupyter/configurable-http-proxy
  npm: name=jupyter/configurable-http-proxy global=yes
  sudo: yes
