---
- name: pull jupyterhub service images
  command: docker pull {{ item }}
  with_items:
  - jupyter/jupyterhub
  - jhamrick/systemuser
  sudo: yes
  tags:
    - docker-rebuild

- name: build jhamrick/lovelace-jupyterhub image
  docker_image:
    path: /home/jhamrick/project/tools/lovelace-jupyterhub
    name: jhamrick/lovelace-jupyterhub
    state: build
  sudo: yes
  tags:
    - docker-rebuild

- name: create the jupyterhub directory
  file: path=/srv/jupyterhub state=directory
  sudo: yes
  tags:
    - docker-rebuild

- name: copy the Dockerfile to the jupyterhub directory
  copy:
    src: Dockerfile
    dest: /srv/jupyterhub/Dockerfile
  sudo: yes
  tags:
    - docker-rebuild

- name: create the userlist
  script: make_userlist.sh /srv/jupyterhub/userlist creates=/srv/jupyterhub/userlist
  sudo: yes
  tags:
    - docker-rebuild

- name: build jhamrick/lovelace-jupyterhub:deploy image
  docker_image:
    path: /srv/jupyterhub
    name: jhamrick/lovelace-jupyterhub
    state: build
    tag: deploy
  sudo: yes
  tags:
    - docker-rebuild
