---
- name: create the userlist
  script: make_userlist.sh {{ jupyterhub_root }}/userlist

- name: install jupyterhub config
  template: src=jupyterhub_config.py dest={{ jupyterhub_root }}/jupyterhub_config.py
