---
- include: dependencies.yml

- name: send interrupt signal to jupyterhub
  shell: "if [ -f {{ jupyterhub_root }}/pid ]; then kill -2 $(cat {{ jupyterhub_root }}/pid); fi"
  tags:
    - stop
    - start

- name: wait for jupyterhub to exit
  wait_for: "path={{ jupyterhub_root }}/pid state=absent"
  tags:
    - stop
    - start

- name: ensure that daemon says jupyterhub is not running
  shell: "[ ! $(daemon -n jupyterhub --running) ]"
  tags:
    - stop
    - start

- include: jupyterhub.yml

- name: start jupyterhub
  command: daemon -n jupyterhub -o {{ jupyterhub_root }}/jupyterhub.log -- /usr/local/bin/jupyterhub -f {{ jupyterhub_root }}/jupyterhub_config.py
  tags:
    - start

- name: ensure jupyterhub is running
  shell: daemon -n jupyterhub --running
  tags:
    - start
