---
- include: docker.yml
- include: docker-build.yml
- include: accounts.yml

- name: stop running docker containers
  shell: docker stop $(docker ps -a -q) || true
  tags:
    - docker-rebuild

- name: remove docker containers
  shell: docker rm $(docker ps -a -q) || true
  tags:
    - docker-rebuild

- name: launch jupyterhub
  docker:
    state: running
    image: jhamrick/lovelace-jupyterhub:deploy
    detach: true
    net: host
    name: jupyterhub
    volumes: /var/run/docker.sock:/docker.sock
  sudo: yes
  tags:
    - docker-rebuild
