---
- name: install apt packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - libprotobuf-dev
    - libleveldb-dev
    - libsnappy-dev
    - libopencv-dev
    - libhdf5-serial-dev
    - protobuf-compiler
    - libatlas-base-dev
    - python-dev
    - libgflags-dev
    - libgoogle-glog-dev
    - liblmdb-dev

- name: install libboost-all-dev
  apt:
    name: libboost-all-dev
    install_recommends: no
    state: latest

- name: clone the caffe repo
  git:
    repo: https://github.com/BVLC/caffe
    update: no
    dest: "{{ caffe_root }}"

- name: install Makefile.config
  copy: src=Makefile.config dest={{ caffe_root }}

- name: install python dependencies
  pip: requirements={{ caffe_root }}/python/requirements.txt

- name: compile caffe (this may take awhile!)
  make:
    target: all
    chdir: "{{ caffe_root }}"
  register: make_all

- name: compile caffe tests (this may take awhile!)
  make:
    target: test
    chdir: "{{ caffe_root }}"
  register: make_test

- name: compile caffe python bindings
  make:
    target: pycaffe
    chdir: "{{ caffe_root }}"
  register: make_pycaffe

- name: run tests (this may take awhile!)
  when: make_all.changed or make_test.changed
  make:
    target: runtest
    chdir: "{{ caffe_root }}"
  environment:
    LD_LIBRARY_PATH: /usr/local/cuda/lib64

- name: run python tests
  when: make_all.changed or make_test.changed or make_pycaffe.changed
  make:
    target: pytest
    chdir: "{{ caffe_root }}"
  environment:
    LD_LIBRARY_PATH: /usr/local/cuda/lib64

- name: update environment variables in global bashrc
  blockinfile:
    dest: /etc/bash.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR CAFFE"
    content: |
      export PYTHONPATH={{ caffe_root }}/python:$PYTHONPATH
