---
- name: install apt packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - libprotobuf-dev
    - libleveldb-dev
    - libsnappy-dev
    - libopencv-dev
    - libhdf5-serial-dev
    - protobuf-compiler
    - libatlas-base-dev
    - python-dev
    - libgflags-dev
    - libgoogle-glog-dev
    - liblmdb-dev

- name: install libboost-all-dev
  apt:
    name: libboost-all-dev
    install_recommends: no
    state: latest

- name: copy over the cuda deb file
  copy: src=cuda-repo-ubuntu1604_8.0.44-1_amd64.deb dest=/root/cuda.deb force=no
  register: cuda_deb

- name: install the cuda deb file
  when: cuda_deb.changed
  shell: dpkg -i /root/cuda.deb

- name: install cuda (this may take awhile!)
  when: cuda_deb.changed
  apt:
    name: cuda
    update_cache: yes
    state: latest

- name: copy over the libcudnn tarball
  copy: src=cudnn-7.0-linux-x64-v4.0-prod.tgz dest=/root/cudnn.tar.gz force=no
  register: libcudnn

- name: extract cudnn
  when: libcudnn.changed
  shell: tar -xf cudnn.tar.gz
  args:
    chdir: /root

- name: get list of cudnn include files
  shell: ls /root/cuda/include/*
  register: cudnn_include

- name: copy cudnn include files
  copy: src={{ item }} remote_src=true dest=/usr/local/cuda/include/
  with_items: '{{ cudnn_include.stdout_lines }}'

- name: get list of cudnn library files
  shell: ls /root/cuda/lib64/*
  register: cudnn_lib64

- name: copy the cudnn library files
  copy: src={{ item }} remote_src=true dest=/usr/local/cuda/lib64/
  with_items: '{{ cudnn_lib64.stdout_lines }}'

- name: clone the caffe repo
  git:
    repo: https://github.com/BVLC/caffe
    version: rc3
    update: yes
    dest: "{{ caffe_root }}"

- name: install Makefile.config
  copy: src=Makefile.config dest={{ caffe_root }}

- name: install python dependencies
  pip: requirements={{ caffe_root }}/python/requirements.txt

- name: compile caffe (this may take awhile!)
  make:
    target: all
    chdir: "{{ caffe_root }}"
  register: make_all

- name: compile caffe tests (this may take awhile!)
  make:
    target: test
    chdir: "{{ caffe_root }}"
  register: make_test

- name: compile caffe python bindings
  make:
    target: pycaffe
    chdir: "{{ caffe_root }}"
  register: make_pycaffe

- name: run tests (this may take awhile!)
  when: make_all.changed or make_test.changed
  make:
    target: runtest
    chdir: "{{ caffe_root }}"
  environment:
    LD_LIBRARY_PATH: /usr/local/cuda/lib64

- name: run python tests
  when: make_all.changed or make_test.changed or make_pycaffe.changed
  make:
    target: pytest
    chdir: "{{ caffe_root }}"
  environment:
    LD_LIBRARY_PATH: /usr/local/cuda/lib64

- name: update environment variables in global bashrc
  blockinfile:
    dest: /etc/bash.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR CAFFE"
    content: |
      export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
      export PYTHONPATH=/usr/local/caffe/python:$PYTHONPATH
